services:
  - type: web
    name: secondmarket-backend
    env: docker
    rootDir: .
    dockerfilePath: Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PROJECT_FILE_UPLOAD_PATH
        value: /var/data/uploads
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    disk:
      name: uploads
      mountPath: /var/data
      sizeGB: 1
