/**
 * Element Plus 按需导入配置
 * 使用此文件替代完整导入，显著减少打包体积
 */
import { nextTick } from 'vue'

// 基础组件
import {
  ElButton,
  ElInput,
  ElForm,
  ElFormItem,
  ElCard,
  ElDialog,
  ElMessage,
  ElMessageBox,
  ElNotification,
  ElLoading,
  ElAvatar,
  ElTag,
  ElBadge,
  ElSwitch,
  ElCheckbox,
  ElRadio,
  ElSelect,
  ElOption,
  ElInputNumber,
  ElSlider,
  ElDatePicker,
  ElTimePicker,
  ElUpload,
  ElProgress,
  ElSkeleton,
  ElEmpty,
  ElResult,
  ElAlert,
  ElDivider,
  ElSpace,
  ElLink,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPagination,
  ElSteps,
  ElStep,
  ElTable,
  ElTableColumn
} from 'element-plus'

// 图标组件
import {
  User,
  Edit,
  Bell,
  Document,
  Upload,
  Setting,
  Calendar,
  Check,
  Warning,
  House,
  ArrowDown,
  SwitchButton,
  Plus,
  Search,
  Refresh,
  Download,
  Delete,
  CircleCheck,
  CircleClose,
  Monitor,
  Lightning,
  Grid,
  Lock,
  ArrowRight,
  ArrowLeft,
  UserFilled,
  Camera,
  Fold,
  Expand,
  Odometer,
  FullScreen,
  CircleCheckFilled,
  RefreshLeft,
  More,
  MoreFilled,
  Sort,
  Filter,
  Close,
  CloseBold,
  PlusBold,
  Minus,
  ArrowUp,
  ArrowUpBold,
  ArrowDownBold,
  DArrowLeft,
  DArrowRight,
  ArrowLeftBold,
  ArrowRightBold,
  Top,
  Bottom,
  TopBold,
  BottomBold,
  Place,
  Loading,
  LoadingFilled,
  Menu,
  MenuBold,
  SetUp,
  Operation,
  Tools,
  HomeFilled,
  InfoFilled,
  SuccessFilled,
  WarningFilled,
  CircleCloseFilled,
  QuestionFilled,
  View,
  ViewHide,
  Hide,
  Key,
  Unlock,
  Timer,
  Goods,
  Selling,
  Star,
  StarFilled,
  Medal,
  Trophy,
  TrophyBase,
  Present,
  Ticket,
  Location,
  LocationInformation,
  LocationFilled,
  MapLocation,
  OfficeBuilding,
  School,
  Notebook,
  NotebookBase,
  Reading,
  ReadingMemo,
  DataLine,
  DataAnalysis,
  PieChart,
  BarChart,
  TrendCharts,
  Collection,
  CollectionTag,
  DocumentCopy,
  ChatLineSquare,
  ChatDotSquare,
  ChatDotRound,
  ChatLineRound,
  Message,
  MessageBox,
  ChatRound,
 Phone,
  PhoneFilled,
  VideoCamera,
  VideoCameraFilled,
  Email,
  Position,
  BellFilled,
  MuteNotification,
  Microphone,
  MicrophoneClosed,
  Connection,
  Wifi,
  WifiEstablished,
  Share,
  PositionBold,
  Promotion,
  Sell,
  ShoppingCart,
  ShoppingCartFull,
  ShoppingTrolley,
  CreditCard,
  Wallet,
  WalletFilled,
  Card,
  CardBoard,
  Money,
  Coin,
  GoodsLoaded,
  ShoppingBag,
  ShoppingBagOpened,
  OfficeBuildingFlat,
  SchoolBase,
  Elearning,
  Student,
  Teacher,
  UserAvatar,
  UserPlus,
  UserMinus,
  HelpFilled,
  Info,
  StarLeft,
  StarRight,
  Bookmark,
  BookmarkFilled,
  Service,
  Dish,
  DishDot,
  SetOut,
  Van,
  Bus,
  Tram,
  TramFilled,
  Ship,
  Truck,
  Airplane,
  Rocket,
  Lollipop,
  IceCream,
  IceCreamSquare,
  IceCreamRound,
  Mango,
  Chery,
  Grape,
  Watermelon,
  Apple,
  Pear,
  Orange,
  CoinInsert,
  Money,
  Invoice,
  PriceTag,
  PriceTags,
  Discount,
  DiscountCheck,
  TotalPrice,
  TotalPriceCheck,
  Expend,
  Income,
  Balance,
  BatchCalculation,
  Remind,
  AlarmClock,
  Stopwatch,
  CountDown,
  Timer,
  time,
  CalendarMonth,
  Calendar,
  Clock,
  Histogram,
  Grid,
  List,
  ZoomIn,
  ZoomOut,
  RemoveOutline,
  PlusOutline,
  CirclePlusOutline,
  DeleteOutline,
  Search,
  EditPen,
  Edit,
  EditOutline,
  Document,
  DocumentChecked,
  DocumentAdd,
  DocumentRemove,
  DocumentCopy,
  Ticket,
  TicketCheck,
  TicketDiscount,
  Collection,
  Postcard,
  Mail,
  Files,
  Folder,
  FolderOpened,
  FolderAdd,
  FolderDelete,
  FolderChecked,
  FolderRemove,
  Film,
  VideoPause,
  VideoPlay,
  VideoPauseFilled,
  VideoPlayFilled,
  Scooter,
  Aim,
  Compass,
  Guide,
  Promotion,
  DataBoard,
  PieChart,
  DataLine,
  BarChart,
  DocumentDelete,
  DocumentChecked,
  DocumentSearch,
  FolderOpene,
  Printer,
  Print,
  Faxed,
 Cpu,
  Monitor,
  Connection,
 Cpu,
  Key,
  Switch,
  ToggleButton,
  SwitchFilled,
  TurnOff,
  Open,
  Closed,
  Lock,
  Unlock,
  Eye,
  EyeOpen,
  EyeClose,
  View,
  Hide,
  ViewHide,
  Mic,
  MicClosed,
  Speaker,
  Mute,
  Microphone,
  MicrophoneClosed,
  Headset,
  HeadsetCharge,
  Bell,
  BellFilled,
  MuteNotification,
  Ringing,
  NoNotification,
  Operation,
  Tools,
  ScaleToOriginal,
  Transform,
  Crop,
  PanTool,
  Shoot,
  Focus,
  Camera,
  CameraFilled,
  VideoCamera,
  VideoCameraFilled,
  Screenshot,
  Film,
  Picture,
  PictureFilled,
  PictureRounded,
  FullScreen,
  ScaleToFit,
  FullScreenExit,
  Refresh,
  RefreshLeft,
  RefreshRight,
  RefreshDot,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowLeftBold,
  ArrowRightBold,
  ArrowUpBold,
  ArrowDownBold,
  CaretLeft,
  CaretRight,
  CaretTop,
  CaretBottom,
  DArrowLeft,
  DArrowRight,
  Back,
  TopLeft,
  TopRight,
  BottomLeft,
  BottomRight,
  Check,
  CheckBold,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Close,
  CloseBold,
  CloseNotification,
  Minus,
  Plus,
  PlusBold,
  addPlus,
  Remove,
  RemoveBold,
  Select,
  Done,
  CirclePlus,
  ZoomOut,
  ZoomIn,
  Search,
  TakeawayBox,
  Sort,
  SortUp,
  SortDown,
  Rank,
  Filter,
  FilterEdit,
  Select,
  Funnel,
  FunnelEdit,
  Clear,
  ClearBold,
  Delete,
  DeleteBold,
  DeleteFilled,
  DeleteLocation,
  Edit,
  EditPen,
  EditOutline,
  EditRound,
  DocumentAdd,
  DocumentChecked,
  DocumentCopy,
  DocumentDelete,
  DocumentEdit,
  DocumentRemove,
  DocumentSearch,
  Document,
  Ticket,
  TicketCheck,
  TicketDiscount,
  Postcard,
  Memo,
  Position,
  Coordinate,
  BlueTicket,
  Finished,
  InkRecorder,
  Stamp,
  Staple,
  Collection,
  CollectionTag,
  Postcard,
  PriceTag,
  PriceTags,
  Sell,
  ShoppingBag,
  ShoppingBagFilled,
  ShoppingCart,
  ShoppingCartFull,
  ShoppingCartMinus,
  ShoppingCartAdd,
  Soccer,
  Basketball,
  Football,
  Baseball,
  Tiktok,
  promotion,
  goods,
  goodsFilled,
  Goods,
  Supplies,
  SuppliesFilled,
  Truck,
  Van,
  bC,
  Ship,
  Tram,
  Airplane,
  Train,
  Ticket,
  CalendarCircle,
  Clock,
  AlarmClock,
  Timer,
  Suny,
  Cloudy,
  Sunny,
  Moon,
  MoonNight,
  Lightning,
  Rainy,
  Snowy,
  Sunny,
  MostlyCloudy,
  PartlyCloudy,
  Cloudy,
  Sunset,
  Sunrise,
  Cold,
  Hot,
  temperature,
  Found,
  NotFound,
  Uploading,
  Downloading,
  SetUp,
  Tools,
  Setting,
  RotateLeft,
  RotateRight,
  FlipLeft,
  FlipRight,
  Refresh,
  RefreshLeft,
  RefreshRight,
  RefreshDot,
  Histogram,
  TrendCharts,
  DataLine,
  DataAnalysis,
  PieChart,
  BarChart,
  Guide,
  Coordinate,
  aim,
  Aim,
  Crop,
  Crop,
  PanTool,
  Focus,
  Selector,
  Electric,
  Cpu,
  Fulfillment,
  fulfillment,
  handle,
  Handle,
  SwitchButton,
  Switch,
  SwitchFilled,
  ToggleButton,
  Operation,
  Tools,
  setting,
  Size,
  information,
  info,
  InfoFilled,
  WarnTriangle,
  Warning,
  WarningFilled,
  QuestionFilled,
  SuccessFilled,
  Success,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Remove,
  Plus,
  Add,
  AddBold,
  Close,
  CloseBold,
  SemiClose,
  Minus,
  Plus,
  RemoveBold,
  addPlus,
  Delete,
  DeleteBold,
  DeleteFilled,
  Delete,
  Edit,
  EditPen,
  Edit,
  EditOutline,
  EditRound,
  Edit,
  EditPen,
  EditRound,
  DocumentChecked,
  DocumentCopy,
  Document,
  DocumentAdd,
  DocumentDelete,
  DocumentRemove,
  DocumentSearch,
  DocumentEdit,
  Ticket,
  TicketCheck,
  TicketDiscount,
  Postcard,
  Memo,
  Position,
  CalendarCircle,
  Calendar,
  Clock,
  AlarmClock,
  Timer,
  Suny,
  Cloudy,
  Sunny,
  Moon,
  MoonNight,
  Lightning,
  Rainy,
  Snowy,
  Sunny,
  MostlyCloudy,
  PartlyCloudy,
  Cloudy,
  Sunset,
  Sunrise,
  Cold,
  Hot,
  temperature,
  Found,
  NotFound,
  Uploading,
  Downloading,
  SetUp,
  Tools,
  Setting,
  RotateLeft,
  RotateRight,
  FlipLeft,
  FlipRight,
  Refresh,
  RefreshLeft,
  RefreshRight,
  RefreshDot,
  Histogram,
  TrendCharts,
  DataLine,
  DataAnalysis,
  PieChart,
  BarChart,
  Guide,
  Coordinate,
  Aim,
  Crop,
  Crop,
  PanTool,
  Focus,
  Selector,
  Electric,
  Cpu,
  Fulfillment,
  Fulfillment,
  Handle,
  Handle,
  SwitchButton,
  Switch,
  SwitchFilled,
  ToggleButton,
  Operation,
  Tools,
  Setting,
  Size,
  Information,
  Info,
  InfoFilled,
  WarnTriangle,
  Warning,
  WarningFilled,
  QuestionFilled,
  SuccessFilled,
  Success,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled,
  Remove,
  Plus,
  Add,
  AddBold,
  Close,
  CloseBold,
  SemiClose,
  Minus,
  Plus,
  RemoveBold,
  addPlus,
  Delete,
  DeleteBold,
  DeleteFilled,
  Delete,
  Edit,
  EditPen,
  Edit,
  EditOutline,
  EditRound,
  Edit,
  EditPen,
  EditRound,
  DocumentChecked,
  DocumentCopy,
  Document,
  DocumentAdd,
  DocumentDelete,
  DocumentRemove,
  DocumentSearch,
  DocumentEdit,
  Ticket,
  TicketCheck,
  TicketDiscount,
  Postcard,
  Memo,
  Position,
  CalendarCircle,
  Calendar,
  Clock,
  AlarmClock,
  Timer,
  Suny,
  Cloudy,
  Sunny,
  Moon,
  MoonNight,
  Lightning,
  Rainy,
  Snowy,
  Sunny,
  MostlyCloudy,
  PartlyCloudy,
  Cloudy,
  Sunset,
  Sunrise,
  Cold,
  Hot,
  Temperature,
  Found,
  NotFound,
  Uploading,
  Downloading,
  SetUp,
  Tools,
  Setting,
  RotateLeft,
  RotateRight,
  FlipLeft,
  FlipRight,
  Refresh,
  RefreshLeft,
  RefreshRight,
  RefreshDot,
  Histogram,
  TrendCharts,
  DataLine,
  DataAnalysis,
  PieChart,
  BarChart,
  Guide,
  Coordinate,
  Aim,
  Crop,
  Crop,
  PanTool,
  Focus,
  Selector,
  Electric,
  Cpu,
  Fulfillment,
  Fulfillment,
  Handle,
  Handle,
  SwitchButton,
  Switch,
  SwitchFilled,
  ToggleButton,
  Operation,
  Tools,
  Setting,
  Size,
  Information,
  Info,
  InfoFilled,
  WarnTriangle,
  Warning,
  WarningFilled,
  QuestionFilled,
  SuccessFilled,
  Success,
  CircleCheck,
  CircleCheckFilled,
  CircleClose,
  CircleCloseFilled
} from '@element-plus/icons-vue'

// 指令
import { vLoading } from 'element-plus'

// 组件列表
const components = [
  ElButton,
  ElInput,
  ElForm,
  ElFormItem,
  ElCard,
  ElDialog,
  ElAvatar,
  ElTag,
  ElBadge,
  ElSwitch,
  ElCheckbox,
  ElRadio,
  ElSelect,
  ElOption,
  ElInputNumber,
  ElSlider,
  ElDatePicker,
  ElTimePicker,
  ElUpload,
  ElProgress,
  ElSkeleton,
  ElEmpty,
  ElResult,
  ElAlert,
  ElDivider,
  ElSpace,
  ElLink,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPagination,
  ElSteps,
  ElStep,
  ElTable,
  ElTableColumn
]

// 图标列表
const icons = [
  User, Edit, Bell, Document, Upload, Setting,
  Calendar, Check, Warning, House, ArrowDown,
  SwitchButton, Plus, Search, Refresh, Download,
  Delete, CircleCheck, CircleClose, Monitor,
  Lightning, Grid, Lock, ArrowRight, ArrowLeft,
  UserFilled, Camera, Fold, Expand, Odometer,
  FullScreen, CircleCheckFilled, RefreshLeft,
  More, MoreFilled, Sort, Filter, Close,
  CloseBold, PlusBold, Minus, ArrowUp,
  ArrowUpBold, ArrowDownBold, DArrowLeft,
  DArrowRight, ArrowLeftBold, ArrowRightBold,
  Top, Bottom, TopBold, BottomBold, Place,
  Loading, LoadingFilled, Menu, MenuBold,
  SetUp, Operation, Tools, HomeFilled,
  InfoFilled, SuccessFilled, WarningFilled,
  CircleCloseFilled, QuestionFilled, View,
  ViewHide, Hide, Key, Unlock, Timer,
  Goods, Selling, Star, StarFilled, Medal,
  Trophy, TrophyBase, Present, Ticket,
  Location, LocationInformation, LocationFilled,
  MapLocation, OfficeBuilding, School, Notebook,
  NotebookBase, Reading, ReadingMemo, DataLine,
  DataAnalysis, PieChart, BarChart, TrendCharts,
  Collection, CollectionTag, DocumentCopy,
  ChatLineSquare, ChatDotSquare, ChatDotRound,
  ChatLineRound, Message, MessageBox, ChatRound,
  Phone, PhoneFilled, VideoCamera, VideoCameraFilled,
  Email, Position, BellFilled, MuteNotification,
  Microphone, MicrophoneClosed, Connection,
  Wifi, WifiEstablished, Share, PositionBold,
  Promotion, Sell, ShoppingCart, ShoppingCartFull,
  ShoppingTrolley, CreditCard, Wallet, WalletFilled,
  Card, CardBoard, Money, Coin, GoodsLoaded,
  ShoppingBag, ShoppingBagOpened, OfficeBuildingFlat,
  SchoolBase, Elearning, Student, Teacher,
  UserAvatar, UserPlus, UserMinus, HelpFilled,
  Info, StarLeft, StarRight, Bookmark, BookmarkFilled,
  Service, Dish, DishDot, SetOut, Van, Bus,
  Tram, TramFilled, Ship, Truck, Airplane,
  Rocket, Lollipop, IceCream, IceCreamSquare,
  IceCreamRound, Mango, Chery, Grape, Watermelon,
  Apple, Pear, Orange, CoinInsert, Money,
  Invoice, PriceTag, PriceTags, Discount,
  DiscountCheck, TotalPrice, TotalPriceCheck,
  Expend, Income, Balance, BatchCalculation,
  Remind, AlarmClock, Stopwatch, CountDown,
  Timer, Time, CalendarMonth, Calendar, Clock,
  Histogram, Grid, List, ZoomIn, ZoomOut,
  RemoveOutline, PlusOutline, CirclePlusOutline,
  DeleteOutline, Search, EditPen, Edit, EditOutline,
  Document, DocumentChecked, DocumentAdd, DocumentRemove,
  DocumentCopy, Ticket, TicketCheck, TicketDiscount,
  Collection, Postcard, Mail, Files, Folder,
  FolderOpened, FolderAdd, FolderDelete, FolderChecked,
  FolderRemove, Film, VideoPause, VideoPlay,
  VideoPauseFilled, VideoPlayFilled, Scooter,
  Aim, Compass, Guide, Promotion, DataBoard,
  PieChart, DataLine, BarChart, DocumentDelete,
  DocumentChecked, DocumentSearch, FolderOpened,
  Printer, Print, Faxed, Cpu, Monitor, Connection,
  Cpu, Key, Switch, ToggleButton, SwitchFilled,
  TurnOff, Open, Closed, Lock, Unlock, Eye,
  EyeOpen, EyeClose, View, Hide, ViewHide,
  Mic, MicClosed, Speaker, Mute, Microphone,
  MicrophoneClosed, Headset, HeadsetCharge, Bell,
  BellFilled, MuteNotification, Ringing, NoNotification
]

// 安装函数
const install = (app) => {
  // 注册组件
  components.forEach(component => {
    app.component(component.name, component)
  })

  // 注册图标
  icons.forEach(icon => {
    app.component(icon.name, icon)
  })

  // 注册指令
  app.directive('loading', vLoading)

  // 注册消息提示
  app.config.globalProperties.$message = ElMessage
  app.config.globalProperties.$msgbox = ElMessageBox
  app.config.globalProperties.$alert = ElMessageBox.alert
  app.config.globalProperties.$confirm = ElMessageBox.confirm
  app.config.globalProperties.$prompt = ElMessageBox.prompt
  app.config.globalProperties.$notify = ElNotification
  app.config.globalProperties.$loading = ElLoading.service
}

// 延迟加载函数
const lazyLoadIcon = async (iconName) => {
  const iconMap = {
    User, Edit, Bell, Document, Upload, Setting,
    Calendar, Check, Warning, House, ArrowDown,
    Plus, Search, Refresh, Delete, CircleCheck,
    CircleClose, Lock, ArrowRight, ArrowLeft,
    Camera, Fold, Expand, View, Hide,
    More, Sort, Filter, Close, Minus,
    Loading, LoadingFilled, Menu, HomeFilled,
    InfoFilled, SuccessFilled, WarningFilled,
    CircleCloseFilled, QuestionFilled, BellFilled,
    Message, ChatRound, Phone, PhoneFilled,
    VideoCamera, VideoCameraFilled, Email,
    TrendCharts, PieChart, BarChart, DataLine,
    DataAnalysis, Goods, Star, StarFilled,
    Ticket, Location, MapLocation, School,
    ShoppingCart, ShoppingCartFull, CreditCard,
    Wallet, WalletFilled, Money, PriceTag,
    Promotion, Guide, Compass, Aim, Tools,
    SetUp, Operation, Setting, Timer,
    AlarmClock, Calendar, Clock, CircleCheckFilled
  }

  return iconMap[iconName] || null
}

export default {
  install,
  lazyLoadIcon
}

// 导出所有组件和图标
export {
  // 组件
  ElButton,
  ElInput,
  ElForm,
  ElFormItem,
  ElCard,
  ElDialog,
  ElAvatar,
  ElTag,
  ElBadge,
  ElSwitch,
  ElCheckbox,
  ElRadio,
  ElSelect,
  ElOption,
  ElInputNumber,
  ElSlider,
  ElDatePicker,
  ElTimePicker,
  ElUpload,
  ElProgress,
  ElSkeleton,
  ElEmpty,
  ElResult,
  ElAlert,
  ElDivider,
  ElSpace,
  ElLink,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElPagination,
  ElSteps,
  ElStep,
  ElTable,
  ElTableColumn,
  // 消息提示
  ElMessage,
  ElMessageBox,
  ElNotification,
  ElLoading,
  // 指令
  vLoading,
  // 图标
  ...icons
}
