BEGIN;

CREATE OR REPLACE FUNCTION set_update_time()
RETURNS TRIGGER AS $$
BEGIN
  NEW.update_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TABLE IF EXISTS browse_history CASCADE;

CREATE TABLE browse_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_browse_user_product UNIQUE (user_id, product_id),
  CONSTRAINT fk_browse_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE,
  CONSTRAINT fk_browse_product FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE
);

DROP TRIGGER IF EXISTS trg_browse_history_update_time ON browse_history;
CREATE TRIGGER trg_browse_history_update_time
BEFORE UPDATE ON browse_history
FOR EACH ROW EXECUTE FUNCTION set_update_time();

COMMIT;
