BEGIN;

CREATE OR REPLACE FUNCTION set_update_time()
RETURNS TRIGGER AS $$
BEGIN
  NEW.update_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TABLE IF EXISTS campus_service CASCADE;

CREATE TABLE campus_service (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  school_id BIGINT,
  type SMALLINT NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT,
  location VARCHAR(200),
  reward NUMERIC(10,2) DEFAULT 0.00,
  limit_count INTEGER,
  current_count INTEGER DEFAULT 0,
  deadline TIMESTAMP,
  status INTEGER NOT NULL DEFAULT 1,
  accepter_id BIGINT,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_campus_service_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE,
  CONSTRAINT fk_campus_service_school FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS trg_campus_service_update_time ON campus_service;
CREATE TRIGGER trg_campus_service_update_time
BEFORE UPDATE ON campus_service
FOR EACH ROW EXECUTE FUNCTION set_update_time();

INSERT INTO campus_service (user_id, school_id, type, title, content, location, reward, status) VALUES
(2, 1, 1, '代取快递 - 菜鸟驿站', '在西门菜鸟驿站有三个大件，求顺路同学带到宿舍楼下。', '西门菜鸟驿站', 5.00, 1),
(3, 1, 2, '外卖拼单 - 霸王茶姬', '想喝霸王茶姬，还差一人免运费，速度来！', '宿舍11栋', 0.00, 1),
(4, 1, 3, '图书馆二楼靠窗位共享', '由于临时有课，座位空出，14:00-16:00可借用。', '图书馆二楼', 0.00, 1);

COMMIT;
