BEGIN;

ALTER TABLE biz_chat
  ADD COLUMN IF NOT EXISTS msg_type INTEGER DEFAULT 0;

ALTER TABLE biz_chat
  ADD COLUMN IF NOT EXISTS is_read SMALLINT DEFAULT 0;

ALTER TABLE forum_post
  ADD COLUMN IF NOT EXISTS is_school_only SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE forum_post
  ADD COLUMN IF NOT EXISTS is_anonymous SMALLINT NOT NULL DEFAULT 0;

ALTER TABLE forum_comment
  ADD COLUMN IF NOT EXISTS is_anonymous SMALLINT NOT NULL DEFAULT 0;

COMMIT;
