BEGIN;

CREATE OR REPLACE FUNCTION set_update_time()
RETURNS TRIGGER AS $$
BEGIN
  NEW.update_time = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TABLE IF EXISTS forum_favorite CASCADE;
DROP TABLE IF EXISTS forum_like CASCADE;
DROP TABLE IF EXISTS forum_comment CASCADE;
DROP TABLE IF EXISTS forum_post CASCADE;

CREATE TABLE forum_post (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  school_id BIGINT,
  category VARCHAR(50) NOT NULL,
  title VARCHAR(100) NOT NULL,
  content TEXT NOT NULL,
  images TEXT,
  is_school_only SMALLINT NOT NULL DEFAULT 0,
  is_anonymous SMALLINT NOT NULL DEFAULT 0,
  view_count INTEGER NOT NULL DEFAULT 0,
  comment_count INTEGER NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_forum_post_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE,
  CONSTRAINT fk_forum_post_school FOREIGN KEY (school_id) REFERENCES school (id) ON DELETE SET NULL
);

DROP TRIGGER IF EXISTS trg_forum_post_update_time ON forum_post;
CREATE TRIGGER trg_forum_post_update_time
BEFORE UPDATE ON forum_post
FOR EACH ROW EXECUTE FUNCTION set_update_time();

CREATE TABLE forum_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  is_anonymous SMALLINT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_forum_comment_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE,
  CONSTRAINT fk_forum_comment_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
);

CREATE TABLE forum_like (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_forum_like_post_user UNIQUE (post_id, user_id),
  CONSTRAINT fk_forum_like_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE,
  CONSTRAINT fk_forum_like_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
);

CREATE TABLE forum_favorite (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_forum_favorite_post_user UNIQUE (post_id, user_id),
  CONSTRAINT fk_forum_favorite_post FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE,
  CONSTRAINT fk_forum_favorite_user FOREIGN KEY (user_id) REFERENCES sys_user (id) ON DELETE CASCADE
);

INSERT INTO forum_post (user_id, school_id, category, title, content, images, view_count, comment_count) VALUES 
(2, 1, '校园闲聊', '求助！首尔大学附近哪里的炸鸡最好吃？', '刚来这边不久，求各位学长学姐推荐一下！最好是那种有校友优惠的店，或者是适合几个人聚餐的地方。感谢大家！', '[]', 120, 24),
(3, 1, '出闲置', '出一些考研/托福资料，半卖半送', '毕业回国了，很多资料带不走。有需要的同学可以私信我。包括历年真题、自己做的笔记，还有一些专业课参考书。地点在延世大学南门。', '[]', 85, 8),
(4, 1, '校园闲聊', '避雷！校门口那家新开的咖啡店千万别去', '态度极差，咖啡味道也一般。等了半个小时才上，而且价格比旁边的贵一倍。真的是避雷了各位！', '[]', 230, 45);

COMMIT;
